baseURL = 'https://blog.scorbiclife.com/'
languageCode = 'en'
title = 'ScorbicLife Blog'
theme = 'PaperMod'


# Multilingual Settings

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
[languages.ko]
